spring.application.name=Gaurav Dev Environment

spring.application.version=1.0-beta

server.port=8081

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs

# Database connection URL (creates a file named localdb.db in your project root)
spring.datasource.url=jdbc:sqlite:app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
